INSERT INTO user VALUES ("kchansuyco", "Karen Chansuyco", "0");
INSERT INTO user VALUES ("jatolentino", "Jas Tolentino", "1");
INSERT INTO user VALUES ("gching", "Gladys Ching", "0");
INSERT INTO user VALUES ("dtalplacido", "Dennis Talplacido", "0");
INSERT INTO user VALUES ("grances", "Gian Rances", "0");
INSERT INTO user VALUES ("palabastro", "Pao Alabastro", "0");

INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("C - A Reference Manual", "C++", "Harbison, Samuel; Steele, Guy", "0-13-326232-4", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Effective C++:  Specific Ways to Improve Your Programs and Designs", "C++", "Meyers, Scott", "978-0-321-33487-9", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("C++ FAQs", "C++ / For Request", "Cline, Marshall; Lomow, Greg; Girou, Mike", "978-0-201-30983-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("C++ FAQs", "C++ / For Request", "Cline, Marshall; Lomow, Greg; Girou, Mike", "978-0-201-30983-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("C++ Primer", "C++ / For Request", "Lippman, Stanley; Lajoie, Josee; Moo, Barbara", "978-0-321-71411-4", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Accelerated C++", "C++ / For Request", "Koenig, Andrew; Moo, Barbara", "978-0-201-70353-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Accelerated C++", "C++ / For Request", "Koenig, Andrew; Moo, Barbara", "978-0-201-70353-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Dictionary of Finance and Investment Terms", "General Reference", "Downes, John; Goodman, Jordan Elliot", "0-7641-2209-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("How to Use Financial Statements: A Guide to Understanding the Numbers", "General Reference", "Bandler, James", "0-7863-0197-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Learning the Vi and Vim Editors", "General Reference", "Robbins, Arnold; Hannah, Elbert; Lamb, Linda", "978-0-596-52983-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Learning the Vi and Vim Editors", "General Reference", "Robbins, Arnold; Hannah, Elbert; Lamb, Linda", "978-0-596-52983-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Learning the Vi and Vim Editors", "General Reference", "Robbins, Arnold; Hannah, Elbert; Lamb, Linda", "978-0-596-52983-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Linux Programmer's Reference", "General Reference", "Petersen, Richard", "0-07-212355-9", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Mastering Regular Expressions", "General Reference", "Friedl, Jeffrey", "978-0-596-52812-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Writing Real Programs in DCL", "General Reference", "Anagnostopoulos, Paul; Hoffman, Steve", "1-5555-8-191-9", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Writing Real Programs in DCL", "General Reference", "Anagnostopoulos, Paul; Hoffman, Steve", "1-5555-8-191-9", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Excel 2010 Power Programming with VBA", "General Reference", "Walkenbach, John", "978-0-470-47535-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Professional Excel Development: The Definitive Guide to Developing Applications Using Microsoft Excel", "VBA and .NET, General Reference", "Bovey, Rob; Wallentin, Dennis; Bullen, Stephen", "978-0-321-508-79-9", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Data Munging with Perl", "Perl", "Cross, David", "1-930110-00-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Data Munging with Perl", "Perl", "Cross, David", "1-930110-00-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Data Munging with Perl", "Perl", "Cross, David", "1-930110-00-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Best Practices", "Perl", "Conway, Damian", "978-0-596-00173-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Best Practices", "Perl", "Conway, Damian", "978-0-596-00173-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Best Practices", "Perl", "Conway, Damian", "978-0-596-00173-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Testing", "Perl", "Langworth, Ian & chromatic", "0-596-10092-2", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Testing", "Perl", "Langworth, Ian & chromatic", "0-596-10092-2", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Perl Testing", "Perl", "Langworth, Ian & chromatic", "0-596-10092-2", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Programming Perl", "Perl", "Wall, Larry; Christiansen, Tom; Orwant, Jon", "978-0-596-00027-1", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Programming Perl", "Perl", "Wall, Larry; Christiansen, Tom; Orwant, Jon", "978-0-596-00027-1", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Don't Make Me Think: A Common Sense Approach to Web Usability", "Software Engineering", "Krug, Steve", "978-0-321-34475-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Refactoring: Improving the Design of Existing Code", "Software Engineering", "Fowler, Martin", "978-0-201-48567-7", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Test-Driven Development: By Example", "Software Engineering", "Beck, Kent", "978-0-321-14653-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("High Performance MySQL", "SQL", "Schwartz, Baron; Zaitsev, Peter; Tkachenko, Vadim", "978-0-596-10171-8", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Pro ASP.NET MVC 3 Framework", "Web", "Freeman, Adam; Sanderson, Steven", "978-1-4302-3404-3", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Ruby on Rails For Dummies", "Web", "Burd, Barry", "9780470081204", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("JavaScript: The Definitive Guide", "Web", "Flanagan, David", "978-0-596-80552-4", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("The Passionate Programmer", "Software Engineering", "Fowler, Chad", "978-1-934356-34-0", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("The Passionate Programmer", "Software Engineering", "Fowler, Chad", "978-1-934356-34-0", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("SQL Antipatterns", "Web", "Karwin, Bill", "978-1-93435-655-5", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Writing Secure Code", "Other/Undefined", "Howard, Michael; LeBlanc David", "0-7356-1722-8", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Peopleware", "Software Engineering", "DeMarco, Tom & Lister, Timothy", "978-0-321-93411-6", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("ReleaseIt!", "Deployment", "Nygard, Michael", "978-0-9787392", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("Inside SQL Server 2008: T-SQL Programming", "SQL", "Ben-Gan, Itzik; Sarka, Dejan; Wolter, Roger", "978-0-7356-2602-7", "1");
INSERT INTO book (title, genre, author, isbn, avail_flag) VALUES ("C++ Common Knowledge", "C++", "Dewhurst, Stephen", "978-0-321-32192-3", "1");
